# Deployment YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
      - name: web
        image: bharath0812/healthcare:2.0
        ports:
        - containerPort: 8082
